### ISSUE TITLE
Add me as a maintainer?

### ISSUE THREAD

**Issue by coderberry** [davidlumley/infusionsoft-api#4]
Hi @davidlumley .. I was wondering if you still use this library. If not, I'd be happy to take over maintenance if you'd like.

**Comment by davidlumley** [comment]
Done! Thanks, always appreciate having help with gems!

**Comment by coderberry** [comment]
Hi @davidlumley .. i ended up forking and adding changes here: https://github.com/cavneb/legacy_infusionsoft_api .. I can bring it back in if you'd like though
